CREATE TABLE wallets
(
    address varchar(40) PRIMARY KEY
) PARTITION BY HASH (address);

CREATE TABLE wallets_p0 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 0);
CREATE TABLE wallets_p1 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 1);
CREATE TABLE wallets_p2 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 2);
CREATE TABLE wallets_p3 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 3);
CREATE TABLE wallets_p4 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 4);
CREATE TABLE wallets_p5 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 5);
CREATE TABLE wallets_p6 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 6);
CREATE TABLE wallets_p7 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 7);
CREATE TABLE wallets_p8 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 8);
CREATE TABLE wallets_p9 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 9);
CREATE TABLE wallets_p10 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 10);
CREATE TABLE wallets_p11 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 11);
CREATE TABLE wallets_p12 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 12);
CREATE TABLE wallets_p13 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 13);
CREATE TABLE wallets_p14 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 14);
CREATE TABLE wallets_p15 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 15);
CREATE TABLE wallets_p16 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 16);
CREATE TABLE wallets_p17 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 17);
CREATE TABLE wallets_p18 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 18);
CREATE TABLE wallets_p19 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 19);
CREATE TABLE wallets_p20 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 20);
CREATE TABLE wallets_p21 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 21);
CREATE TABLE wallets_p22 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 22);
CREATE TABLE wallets_p23 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 23);
CREATE TABLE wallets_p24 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 24);
CREATE TABLE wallets_p25 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 25);
CREATE TABLE wallets_p26 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 26);
CREATE TABLE wallets_p27 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 27);
CREATE TABLE wallets_p28 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 28);
CREATE TABLE wallets_p29 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 29);
CREATE TABLE wallets_p30 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 30);
CREATE TABLE wallets_p31 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 31);
CREATE TABLE wallets_p32 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 32);
CREATE TABLE wallets_p33 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 33);
CREATE TABLE wallets_p34 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 34);
CREATE TABLE wallets_p35 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 35);
CREATE TABLE wallets_p36 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 36);
CREATE TABLE wallets_p37 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 37);
CREATE TABLE wallets_p38 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 38);
CREATE TABLE wallets_p39 PARTITION OF wallets
    FOR VALUES WITH (MODULUS 40, REMAINDER 39);
